### ISSUE TITLE
Which docker image can I use to run the github action

### ISSUE THREAD

**Issue by wenwenchenbosch** [Azure/powershell#104]
I want to use this github action to run inlineScript. The github should be running in a docker container, but I can not find any official image for this purpose.

My workflow file looks similar to the one in [README](https://github.com/Azure/powershell/blob/master/README.md#sample-workflow). I only added `container`:
```
on: [push]

name: AzurePowerShellSample

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ???
    steps:
    
    - name: Login via Az module
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell inline script
      uses: azure/powershell@v2
      with:
        inlineScript: |
          Get-AzVM -ResourceGroupName "ResourceGroup11"
        azPSVersion: "latest"
```

With `image: mcr.microsoft.com/azure-powershell:latest` I get error `Error: Login failed with Error: Unable to locate executable file: az. ` in login step.
With `image:mcr.microsoft.com/azure-cli:latest` I get error `Error: Unable to locate executable file: pwsh.`

Can someone help me? Or I need a customer docker image for running this simple workflow?

**Comment by YanaXu** [comment]
Hi @wenwenchenbosch , it's the limitation that if you want to use Azure Login Action, Azure cli and Azure PowerShell should be installed on your runner.
May I ask why you need run the Azure PowerShell script in a docker container? It's not a suggested way to run it. You know many softwares are not installed in many docker images.

The images you have tried are only with Azure Cli or Azure PowerShell, not both of them. That's why it failes.

If you do need to run a docker image (only with Azure PowerShell but without Azure Cli) to run Azure PowerShell script in GitHub actions, I suggest you to login with Azure PowerShell directly instead of using Azure Login Action.
For example

```yaml
    - name: GetFederatedToken
      uses: actions/github-script@v4
      with:
        script: |
          const idToken = await core.getIDToken('api://AzureADTokenExchange')
          core.exportVariable('idToken', idToken)

    - name: OIDCLoginAndRunAzurePowerShell
      shell: pwsh
      env: 
        tenantId: ${{secrets.tenantId }}
        subscriptionId: ${{secrets.subscriptionId }}
        clientId: ${{secrets.clientId}}
      run: |
        Connect-AzAccount -ServicePrincipal -ApplicationId $env:clientId -Tenant $env:tenantId -SubscriptionId $env:subscriptionId -FederatedToken $env:idToken
        # run your azure powershell cmdlets
        # ...

```
