### ISSUE TITLE
Az.ImageBuilder module could not be loaded

### ISSUE THREAD

**Issue by GPJDE** [Azure/powershell#105]
modules are installed from PSGallery 
Run azure/powershell@v1 using the shell PWSH

Calls an inline script and stops with error:
 "The 'Get-AzImageBuilderTemplate' command was found in the module 'Az.ImageBuilder', but the module could not be
     | loaded. For more information, run 'Import-Module Az.ImageBuilder'.
Error: Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1"

We have 3 separate workflows and all fails due to this error. Please guide.

**Comment by YanaXu** [comment]
Hi @GPJDE ,  there are 2 issues in your workflow file.
- The first one is about how to use the right Azure PowerShell version with Azure PowerShell Action.
If you want to use the specific Azure PowerShell version, please set the value of "**azPSVersion**". E.g.
```yaml
      - name: Run powershell command in US Gov Cloud
        uses: azure/powershell@v2
        with:
          inlineScript: "Get-AzContext"
          azPSVersion: "11.6.0"
```
You can find all Azure PowerShell versions on [PSGallery](https://www.powershellgallery.com/packages/Az).

- The second one is about how to install "Az.ImageBuilder". According to [Az.ImageBuilder](https://www.powershellgallery.com/packages/Az.ImageBuilder), this module is not GAed yet. That means it's not included by `Az`. You can check the "Package Details" of [Az](https://www.powershellgallery.com/packages/Az/11.6.0).
Please install [AzPreview](https://www.powershellgallery.com/packages/AzPreview) instead. Or install [Az.ImageBuilder](https://www.powershellgallery.com/packages/Az.ImageBuilder) directly.
