### ISSUE TITLE
Add script file execution support

### ISSUE THREAD

**Issue by Satak** [Azure/powershell#15]
Currently only way to run Powershell script is to add the script as inline inside the yaml file. This can be very messy in bigger scripts. Add support to execute Powershell script file from the current repository.

Example:

```yaml
on: [push]

name: AzurePowerShellSample

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        scriptFile: ./my-script.ps1
```
