### ISSUE TITLE
Step succeeds while error stream is written

### ISSUE THREAD

**Issue by geekzter** [Azure/powershell#33]
Hi,

On my workflow step, I have configured:
```
errorActionPreference: Stop
failOnStandardError: true
```
Still the step succeeds, as can be seen below:
<img width="590" alt="Screen Shot 2021-04-02 at 17 45 05" src="https://user-images.githubusercontent.com/18408391/113431110-8bf2d400-93db-11eb-831c-2a330b30499d.png">

**Comment by BALAGA-GAYATRI** [comment]
Hi @geekzter , Can you share your workflow here.

**Comment by kanika1894** [comment]
@geekzter any updates?

**Comment by geekzter** [comment]
Hi @kanika1894,

The workflow I use is at https://github.com/geekzter/azure-minecraft-docker/blob/main/.github/workflows/ci-vanilla.yml (line 173):
```yaml
    - name: Test connection to Minecraft Server (pwsh)
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      uses: Azure/powershell@v1
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      with:
        inlineScript: | 
          # Wait for Minecraft to boot up
          $connectionAttempts = 0
          do {
            Start-Sleep -Seconds 10
            Write-Host "Pinging ${env:TF_OUT_minecraft_server_fqdn} on port ${env:TF_OUT_minecraft_server_port}..."
            try {
              $connectionAttempts++
              $mineCraftConnection = New-Object System.Net.Sockets.TcpClient($env:TF_OUT_minecraft_server_fqdn, $env:TF_OUT_minecraft_server_port) -ErrorAction SilentlyContinue
            } catch [System.Management.Automation.MethodInvocationException] {
              Write-Warning $_
            }
          } while ((!$mineCraftConnection || !$mineCraftConnection.Connected) -and ($connectionAttempts -le 10))
          
          az container show --ids ${{ steps.terraform-apply.outputs.container_group_id }} --query instanceView
          az container logs --ids ${{ steps.terraform-apply.outputs.container_group_id }}
          # BUG: no tty
          # az container exec --ids ${{ steps.terraform-apply.outputs.container_group_id }} --exec-command "rcon-cli say hello from ci" --container-name minecraft
        azPSVersion: latest
        errorActionPreference: Stop
        failOnStandardError: true # BUG: setting not honored! `https://github.com/Azure/powershell/issues/33`
```

I've learned that this task is not really needed if you use azure/login@v1 and then the stock run task with shell pwsh.
