### ISSUE TITLE
Error parsing boolean value. Path '', line 1, position 1.

### ISSUE THREAD

**Issue by dkirrane** [Azure/powershell#44]
I'm attempting to deploy a Bicep file that I don't have issues deploying locally

I keep hitting `Error parsing boolean value. Path '', line 1, position 1.`

```
    - name: Bicep Hyperscale
      uses: azure/powershell@v1.1.0
      with:
        azPSVersion: '3.5.0'
        inlineScript: |
          Set-Location ${{ github.workspace }}/script/
          New-AzResourceGroupDeployment -ResourceGroupName "test-rg" -TemplateFile my.bicep -Mode Incremental
```
