### ISSUE TITLE
Add support for action input fromFile:

### ISSUE THREAD

**Issue by Pwd9000-ML** [Azure/powershell#49]
Is it possible to add support for running a script from a file location inside of the repo, rather than embedding the script "inline"?

**Example:**

```yml
inputs:
  inlineScript:
    description: 'Specify the Az PowerShell script here.'
    required: false

  fromFile:
    description: 'Path to script file relevant to repo root, default "." '
    required: false
    default: .
```

**Comment by BALAGA-GAYATRI** [comment]
We marked this as an enhancement request and will be discussed. We shall keep you updated if it is decided to implement. Thanks!

**Comment by bogdan-grozoiu** [comment]
Hi, any traction here?

**Comment by YanaXu** [comment]
Hi @bogdan-grozoiu ，

If you have an Azure PowerShell script file in your GitHub repo, have you tried to run it directly?
An example like this (Assume the script file is `./scripts/test1.ps1` and it's right in the root folder of your GitHub repo.):
```yaml
    - name: Check Out
      uses: actions/checkout@v3
    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v1
      with:
        inlineScript: ./scripts/test1.ps1
        azPSVersion: "latest"
```
