### ISSUE TITLE
set-output On Git Action Fails

### ISSUE THREAD

**Issue by briglx** [Azure/powershell#51]
The output parameter for the task is always blank.

```
- name: Set Parameter
  id: task-set-parameter
  uses: azure/powershell@v1
  with:
    inlineScript: |
      Write-Output ::set-output name=my_param::"test"
    azPSVersion: "latest"

- name: Read Parameter
  uses: azure/powershell@v1
  with:
    inlineScript: |
      Write-Output '${{ steps.task-set-parameter.ouputs.my_param}}'
    azPSVersion: "latest"
```

**Comment by BALAGA-GAYATRI** [comment]
Hey @briglx , we shall investigate this and keep you posted.

**Comment by BALAGA-GAYATRI** [comment]
Hey @briglx 
here is my sample using both `pwsh` shell and `azure/powershell` action. Both are returning the output for me.
```yaml
name: Check outputs
on: workflow_dispatch

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
     
      - name: Set outputs
        id: vars
        shell: pwsh
        run: echo "::set-output name=production::true"

      - name: Check outputs
        shell: pwsh
        run: echo ${{ steps.vars.outputs.production }}
  
      - name: Set Parameter
        id: tasksetparameter
        uses: azure/powershell@v1
        with:
            inlineScript: |
                  echo "::set-output name=production::true"
            azPSVersion: latest

      - name: Read Parameter
        uses: azure/powershell@v1
        with:
           inlineScript: |
             echo ${{ steps.tasksetparameter.outputs.production }}
           azPSVersion: latest
```
[workflow logs](https://github.com/BALAGA-GAYATRI/azure-login-action-tests/runs/5590564247?check_suite_focus=true) for reference.  Also I see that there is a typo in your "steps.task-set-parameter.**ouputs**.my_param".
Closing this issue.
