### ISSUE TITLE
GitHub Actions - Please update the following actions to use Node.js 16: azure/powershell

### ISSUE THREAD

**Issue by JulianHayward** [Azure/powershell#58]
how to handle that?

<img width="918" alt="image" src="https://user-images.githubusercontent.com/45695032/195278938-9914baad-cc41-4ca7-8ee5-7c6eeac57594.png">

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: azure/powershell, azure/powershell

```
     - name: getCtx
       uses: azure/powershell@v1
       with:
        inlineScript: |
          Get-AzContext
        azPSVersion: "latest"
```
