### ISSUE TITLE
Action does not use Azure context set by azure/login step

### ISSUE THREAD

**Issue by bobmeyers5** [Azure/powershell#8]
I created a workflow that simply connects to Azure and calls Get-AzSubscription. It follows the sample in the [README.md file](https://github.com/Azure/powershell/blob/master/README.md) for this action almost exactly.

* When I run the workflow on the `windows-latest` GitHub-hosted runner ([installed software](https://github.com/actions/virtual-environments/blob/win19/20200517.1/images/win/Windows2019-Readme.md)), it **succeeds**.

* When I run the workflow on a self-hosted runner with the same (relevant) software, the azure/login step succeeds:

```
Azure PowerShell session successfully initialized
Login successful.
```

...but the azure/powershell step **fails** with this error:

```
Run Connect-AzAccount to login.
```

Here's the entire workflow:

```
name: Connect to Azure
on:
  push:
    branches: master
    paths: 
    - '.github/workflows/connect-to-azure.yml'
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_DEPLOYMENT_SERVICE_PRINCIPAL}}
        enable-AzPSSession: true
      
    - name: Deploy app package
      uses: azure/powershell@v1
      with:
        azPSVersion: latest
        inlineScript: Get-AzSubscription -SubscriptionId "<my-subscription-id>"
```

**Both** environments have the following software installed:
* GitHub runner 2.262.1
* PowerShell Core 7.0.1
* Azure CLI 2.5.1
* Az 3.8.0
* Az.Accounts 1.7.5

What am I missing? This workflow should be trivial to get working on a self-hosted runner.

Additional info:
- The self-hosted runner OS is Windows 10 Pro 18362.
- I get the same error with the following software versions installed:
  * PowerShell Core 6.2.4
  * Azure CLI 2.6.0
  * Az 3.8.0
  * Az.Accounts 1.8.0
- I can connect to Azure successfully on the self-hosted runner using this PS command, which is the same as what the [azure/login action](https://github.com/Azure/login/blob/master/src/PowerShell/Utilities/ScriptBuilder.ts) does:

```
Connect-AzAccount -ServicePrincipal -Tenant <tenant-id> -Credential <service-principal-creds> -Environment AzureCloud
```
